"""initial tables

Revision ID: c1b09c789caa
Revises: 032884e66f6c
Create Date: 2025-04-16 16:13:57.320951

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa 


# revision identifiers, used by Alembic.
revision: str = 'c1b09c789caa'
down_revision: Union[str, None] = '032884e66f6c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###
