"""initial tables

Revision ID: 36d04cac8614
Revises: e2fdb1559ca8
Create Date: 2025-04-16 22:37:15.883722

"""
from typing import Sequence, Union

from alembic import op  # type: ignore
import sqlalchemy as sa # type: ignore


# revision identifiers, used by Alembic.
revision: str = '36d04cac8614'
down_revision: Union[str, None] = 'e2fdb1559ca8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('food_items', sa.Column('brands', sa.String(), nullable=True))
    op.add_column('food_items', sa.Column('quantity', sa.Integer(), nullable=True))
    op.add_column('food_items', sa.Column('energy', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('food_items', 'energy')
    op.drop_column('food_items', 'quantity')
    op.drop_column('food_items', 'brands')
    # ### end Alembic commands ###
