"""Initial tables

Revision ID: 452fa3f87c2b
Revises: e1e90e8e4fbc
Create Date: 2025-05-15 19:15:10.383231

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '452fa3f87c2b'
down_revision: Union[str, None] = 'e1e90e8e4fbc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    pass


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass